services:
  - type: web
    name: eventverse-api
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /
    autoDeployTrigger: commit
    envVars:
      - key: NODE_VERSION
        value: 22.21.1
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: BCRYPT_ROUNDS
        value: 12
      - key: CLIENT_URL
        value: https://exe-201-fpt7.vercel.app
      - key: SERVER_PUBLIC_URL
        value: https://eventverse-api.onrender.com
      - key: PAYOS_CLIENT_ID
        sync: false
      - key: PAYOS_API_KEY
        sync: false
      - key: PAYOS_CHECKSUM_KEY
        sync: false
